# Generated by Django 3.0.5 on 2020-05-14 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='ultimo',
            field=models.BooleanField(default=False),
        ),
    ]
