# Generated by Django 3.0.5 on 2020-05-03 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_suscriptoruser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SuscriptorUser',
            new_name='User',
        ),
    ]
