# Generated by Django 3.0.5 on 2020-05-05 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200505_1515'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Suscriptor',
        ),
    ]
