# Generated by Django 3.0.5 on 2020-05-15 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200514_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='novedad',
            name='archivo',
            field=models.FileField(blank=True, upload_to='images/'),
        ),
    ]
