# Generated by Django 3.0.5 on 2020-05-07 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_delete_suscriptor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarjeta',
            name='nombreTitular',
        ),
        migrations.AddField(
            model_name='tarjeta',
            name='dni',
            field=models.IntegerField(default=None),
        ),
    ]
