# Generated by Django 3.0.5 on 2020-05-08 03:27

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_delete_suscriptor'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='tarjeta',
            managers=[
                ('Tarjeta', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='tipotarjeta',
            managers=[
                ('TipoTarjeta', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='tarjeta',
            name='idTipoTarjeta',
        ),
        migrations.RemoveField(
            model_name='tarjeta',
            name='nombreTitular',
        ),
        migrations.AddField(
            model_name='tarjeta',
            name='dni',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tarjeta',
            name='tipo',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='clave',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='fechaVencimiento',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='numero',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='idTarjeta',
            field=models.IntegerField(default=0),
        ),
    ]
