# Generated by Django 3.0.5 on 2020-05-03 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_user_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='apellido',
            field=models.CharField(default='fulanito', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='nombre',
            field=models.CharField(default='pepe', max_length=50),
            preserve_default=False,
        ),
    ]
