# Generated by Django 3.0.5 on 2020-05-09 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200508_0027'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='configuracion',
            name='Premium',
        ),
        migrations.RemoveField(
            model_name='configuracion',
            name='Standar',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='editorial',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='genero',
        ),
        migrations.AlterField(
            model_name='libro',
            name='descripcion',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='libro',
            name='isbn',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='novedad',
            name='descripcion',
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name='libro',
            name='idAutor',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Autor'),
        ),
        migrations.AddField(
            model_name='libro',
            name='idEditorial',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Editorial'),
        ),
        migrations.AddField(
            model_name='libro',
            name='idGenero',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Genero'),
        ),
    ]
