# Generated by Django 3.0.5 on 2020-05-16 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200515_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='novedad',
            name='titulo',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
