# Generated by Django 3.0.5 on 2020-05-22 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200521_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capitulo',
            name='archivo',
            field=models.FileField(upload_to='static/file/'),
        ),
    ]
