# Generated by Django 3.0.5 on 2020-05-22 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200522_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capitulo',
            name='fechaLanzamiento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='capitulo',
            name='fechaVencimiento',
            field=models.DateField(),
        ),
    ]
