# Generated by Django 3.0.5 on 2020-05-09 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200508_2139'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Capitulos',
            new_name='Capitulo',
        ),
    ]
