# Generated by Django 3.0.5 on 2020-05-16 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200515_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novedad',
            name='archivo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
