# Generated by Django 3.0.5 on 2020-05-16 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200515_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='novedad',
            name='archivoVideo',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
