# Generated by Django 3.0.5 on 2020-05-07 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200507_0353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjeta',
            name='idTipoTarjeta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.TipoTarjeta'),
        ),
    ]
