# Generated by Django 3.0.5 on 2020-05-07 23:06

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200507_0356'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='tarjeta',
            managers=[
                ('Tarjeta', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='tipotarjeta',
            managers=[
                ('TipoTarjeta', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='tarjeta',
            name='idTipoTarjeta',
        ),
        migrations.AddField(
            model_name='tarjeta',
            name='tipoTarjeta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.TipoTarjeta'),
        ),
    ]
