# Generated by Django 3.0.5 on 2020-05-16 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_novedad_archivovideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novedad',
            name='archivo',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/'),
        ),
    ]
