# Generated by Django 3.0.5 on 2020-05-28 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200527_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capitulo',
            name='idLibro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Libro'),
        ),
    ]
