# Generated by Django 3.0.5 on 2020-05-09 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200509_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='foto',
            field=models.ImageField(null=True, upload_to='static/images/'),
        ),
    ]
