# Generated by Django 3.0.5 on 2020-05-28 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20200527_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capitulo',
            name='idLibro',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, to='app.Libro'),
            preserve_default=False,
        ),
    ]
