# Generated by Django 3.0.5 on 2020-05-07 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20200507_2006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarjeta',
            old_name='tipoTarjeta',
            new_name='tipo',
        ),
    ]
