# Generated by Django 3.0.5 on 2020-05-07 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200507_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjeta',
            name='tipo',
            field=models.IntegerField(default=0),
        ),
    ]
