# Generated by Django 3.0.5 on 2020-05-30 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20200528_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capitulo',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
