# Generated by Django 3.0.5 on 2020-05-11 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20200509_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='idAutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Autor'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='idEditorial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Editorial'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='idGenero',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Genero'),
        ),
    ]
