# Generated by Django 3.0.5 on 2020-05-16 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20200516_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novedad',
            name='archivoVideo',
            field=models.FileField(blank=True, null=True, upload_to='static/videos/'),
        ),
    ]
