# Generated by Django 3.0.5 on 2020-05-12 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20200511_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='vistos',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='capitulo',
            name='idLibro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Libro'),
        ),
    ]
