# Generated by Django 3.0.5 on 2020-06-03 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20200530_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='capitulo',
            name='numero',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
