# Generated by Django 3.0.5 on 2020-05-12 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20200511_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjeta',
            name='fechaVencimiento',
            field=models.DateField(),
        ),
    ]
