# Generated by Django 3.0.5 on 2020-05-13 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20200512_0205'),
        ('app', '0013_auto_20200512_0318'),
    ]

    operations = [
    ]
