# Generated by Django 3.0.5 on 2020-06-05 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20200602_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='fechaLanzamientoFinal',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='fechaVencimientoFinal',
            field=models.DateField(null=True),
        ),
    ]
