# Generated by Django 3.0.5 on 2020-06-09 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20200606_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='LibroEnCapitulos',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='capitulo',
            name='nombre',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
