# Generated by Django 3.0.5 on 2020-06-10 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20200609_2018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='fechaLanzamientoFinal',
        ),
    ]
