# Generated by Django 3.0.5 on 2020-06-13 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_remove_libro_fechalanzamientofinal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capitulo',
            name='idLibro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Libro'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/'),
        ),
    ]
