# Generated by Django 3.0.7 on 2020-06-12 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_remove_libro_fechalanzamientofinal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Historial',
        ),
    ]
