# Generated by Django 3.0.5 on 2020-06-13 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20200612_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='historial',
            name='terminado',
            field=models.BooleanField(default=False),
        ),
    ]
