# Generated by Django 3.0.5 on 2020-06-14 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20200612_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capitulo',
            name='numero',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
