# Generated by Django 3.0.5 on 2020-06-13 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_perfilactual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historial',
            name='idLibro',
        ),
        migrations.AddField(
            model_name='historial',
            name='idCapitulo',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.Capitulo'),
            preserve_default=False,
        ),
    ]
