# Generated by Django 3.0.7 on 2020-06-14 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_historial_perfilactual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
