# Generated by Django 3.0.7 on 2020-06-14 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20200614_1847'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PerfilActual',
        ),
    ]
