# Generated by Django 3.0.7 on 2020-06-15 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_perfilactual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capitulo',
            name='numero',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
