# Generated by Django 3.0.5 on 2020-07-07 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_perfilactual'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('texto', models.CharField(max_length=256)),
                ('puntaje', models.IntegerField()),
                ('spoiler', models.BooleanField(default=False)),
                ('idPerfil', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Perfil')),
            ],
        ),
    ]
