# Generated by Django 3.0.5 on 2020-07-07 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_review_idlibro'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='nombre',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
