# Generated by Django 3.0.5 on 2020-07-02 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_user_datecreate'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='lecturaEnCurso',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='libro',
            name='lecturaTerminada',
            field=models.IntegerField(default=0),
        ),
    ]
