# Generated by Django 3.0.5 on 2020-07-10 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_auto_20200701_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='capitulo',
            name='ultimoCapitulo',
            field=models.BooleanField(default=False),
        ),
    ]
