# Generated by Django 3.0.5 on 2020-07-07 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_review_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='spoilerAdmin',
            field=models.BooleanField(default=False),
        ),
    ]
