# Generated by Django 3.0.5 on 2020-07-09 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_favorito'),
        ('app', '0030_auto_20200701_2115'),
    ]

    operations = [
    ]
