# Generated by Django 3.0.5 on 2020-07-11 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_capitulo_ultimocapitulo'),
        ('app', '0033_merge_20200709_1443'),
    ]

    operations = [
    ]
