# Generated by Django 3.0.7 on 2020-07-13 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_auto_20200709_2023'),
        ('app', '0031_capitulo_ultimocapitulo'),
    ]

    operations = [
    ]
